#include <avr/io.h>
#include <avr/interrupt.h>
#include <util/atomic.h>
#include <stdint.h>
#include <stdbool.h>

/* Top value for Timer1 Fast PWM Mode 14 (1 kHz @ F_CPU = 16 MHz, Prescaler = 8) */
#define PWM_TOP 1999U

/* System tick variable generated by Timer0 CTC (1 ms) */
static volatile uint32_t system_ticks_ms = 0;

ISR(TIMER0_COMPA_vect) {
    system_ticks_ms++;
}

static uint32_t get_system_ticks_ms(void) {
    uint32_t ticks;
    ATOMIC_BLOCK(ATOMIC_RESTORESTATE) {
        ticks = system_ticks_ms;
    }
    return ticks;
}

/* 
 * Safely updates Timer1 OC1A duty cycle percentage using integer arithmetic.
 * OCR1A = (duty_percent * (ICR1 + 1)) / 100
 */
static void pwm_set_duty_percent(uint8_t duty_percent) {
    if (duty_percent > 100) {
        duty_percent = 100;
    }
    OCR1A = ((uint32_t)duty_percent * (PWM_TOP + 1U)) / 100U;
}

static void timer0_init_system_tick(void) {
    TCCR0A = (1 << WGM01);                  /* CTC Mode */
    TCCR0B = 0;
    OCR0A = 249;                            /* 1 ms tick @ 16 MHz / 64 */
    TIMSK0 = (1 << OCIE0A);                 /* Compare match A interrupt enable */
    TCCR0B |= (1 << CS01) | (1 << CS00);    /* Prescaler = 64 */
}

static void timer1_init_pwm(void) {
    /* 1. Configure PB1 / OC1A (DIP-28 Pin 15) as digital output */
    DDRB |= (1 << DDB1);

    /* 2. Configure Timer1 for Fast PWM Mode 14 (TOP = ICR1, WGM13:10 = 1110) */
    /* Non-inverting compare mode on OC1A (COM1A1 = 1, COM1A0 = 0) */
    TCCR1A = (1 << COM1A1) | (1 << WGM11);
    TCCR1B = (1 << WGM13) | (1 << WGM12);

    /* 3. Set TOP counter value for 1.0 kHz PWM frequency */
    ICR1 = PWM_TOP;

    /* 4. Set initial duty cycle to 50% (OCR1A = 1000) */
    pwm_set_duty_percent(50);

    /* 5. Start Timer1 clock with Prescaler = 8 (CS12:0 = 010) */
    TCCR1B |= (1 << CS11);
}

int main(void) {
    /* Initialize peripherals */
    timer0_init_system_tick();
    timer1_init_pwm();

    /* Enable global interrupts */
    sei();

    static const uint8_t duty_sequence[] = {25, 50, 75};
    uint8_t seq_index = 0;
    uint32_t last_step_ms = 0;

    /* Non-blocking main super-loop */
    while (1) {
        uint32_t current_ms = get_system_ticks_ms();

        /* Cycle through duty sequence (25% -> 50% -> 75%) every 2000 ms */
        if ((current_ms - last_step_ms) >= 2000U) {
            last_step_ms = current_ms;

            seq_index = (seq_index + 1) % 3;
            pwm_set_duty_percent(duty_sequence[seq_index]);
        }
    }

    return 0;
}
